num1=4
num2=2
suma= num1 + num2 
resta= num1 - num2
multiplicacion= num1 * num2
division= num1 / num2
cuadrado=num2 * num2
print(f"El resultado de la suma es = {suma}")
print(f"El resultado de la resta es = {resta}")
print(f"El resultado de la multiplicacion es = {multiplicacion}")
print(f"El resultado de la division es = {division}")
print(f"El cuadrado del segundo valor es = {cuadrado}")